version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3Uploader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12xtmy2749plc"
s3_prefix = "s3Uploader"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
